# Generated by Django 5.2.4 on 2025-07-13 10:37

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MathSparsh', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logo/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='site_banner/')),
                ('homepage_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Homepage dynamic content (supports rich text and LaTeX)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='answerkey',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Use LaTeX for equations.'),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Use LaTeX for equations.'),
        ),
        migrations.AddField(
            model_name='solution',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Use LaTeX for equations.'),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to='core.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='core.question'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.CreateModel(
            name='AnswerKeyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='answerkey_images/')),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.answerkey')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('is_correct', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='option_images/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='question_images/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='solution_images/')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.solution')),
            ],
        ),
    ]
